---
title: "Codebook"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
targets::tar_load(DF_clean)
DF = DF_clean

```

## Summary

```{r summary, include=FALSE}

number_participants = DF %>% distinct(id) %>% nrow()

number_tasks = DF %>% distinct(experimento) %>% nrow()

```

A total of `r number_participants` people completed `r number_tasks` tasks.  


### By participant  

```{r summary-table, echo=FALSE}

summary_table = 
  DF %>% 
    group_by(id) %>% 
    summarise(
      n_tasks = n_distinct(experimento),
      time_elapsed = max(time_elapsed) / 1000,
      rt = sum(rt) / 1000,
      time_elapsed_min = max(time_elapsed) / 60,
      rt_min = sum(rt) / 60, 
      .groups = "keep"
      )

knitr::kable(summary_table)
```


### By experiment  

```{r summary-table2, echo=FALSE}

summary_table2 = 
  DF %>% 
  group_by(experimento) %>% 
  summarise(
    n_participants = n_distinct(id),
    time_elapsed = max(time_elapsed) / 1000,
    rt = sum(rt) / 1000,
    time_elapsed_min = max(time_elapsed) / 60,
    rt_min = sum(rt) / 60, 
    .groups = "keep"
  )

knitr::kable(summary_table2)
```

### Order of tasks

```{r summary-position, echo=FALSE}
summary_position = DF %>% 
  distinct(id, experimento, datetime) %>% 
  group_by(id) %>% 
  arrange(id, (datetime)) %>% 
  mutate(Order = row_number()) %>% 
  select(-datetime) %>% 
  group_by(experimento) %>% 
  summarise(MEAN_Position = mean(Order),
            SD_Position = sd(Order), 
            MIN_Position = min(Order), 
            MAX_Position = max(Order), .groups = "drop") %>% 
  arrange(MEAN_Position, experimento)

knitr::kable(summary_position)

```



## Details of tasks

```{r echo=FALSE}

# Alternative trialid for each scale
trialid_table = DF %>% 
  filter(trial_type != "fullscreen") %>% 
  select(experimento, trial_type, trialid, responses) %>% 
  # filter(trial_type %in% c("survey-multi-choice-vertical", "survey-multi-choice-horizontal", "likert", "html-slider-response")) %>% 
  group_by(experimento) %>% 
  distinct(trialid) %>% 
  count(experimento, name = "number_items")


DT::datatable(trialid_table, filter = 'top', options = list(dom = 'tip'))

```


## Details of tasks  

Trialid's and questions for each of the items:  

```{r echo=FALSE}

# trialid and question_text for each experiment
trialid_detail_table = DF %>% 
  select(experimento, trialid, stimulus) %>% 
  group_by(experimento) %>% 
  distinct(trialid, stimulus) 


DT::datatable(trialid_detail_table, filter = 'top', options = list(dom = 'tip'))
```


## Details Responses

### Only showing multi-choice, slider and liker scales

```{r echo=FALSE}

# Alternatives responses for each scale
responses_table = DF %>% 
  # distinct(trial_type)
  select(experimento, trial_type, trialid, responses) %>% 
  filter(trial_type %in% c("survey-multi-choice-vertical", "survey-multi-choice-horizontal", "likert", "html-slider-response")) %>% 
  group_by(experimento) %>% 
  distinct(trialid, responses) 


DT::datatable(responses_table, filter = 'top', options = list(dom = 'tip'))

```


```{r echo=FALSE}
  # DF_responses =
  #   DF_long_RAW %>% 
  #   count(trialid, RAW) %>% 
  #   group_by(trialid) %>% 
  #   summarise(N = n(),
  #             Responses = paste(RAW, collapse = ", "), 
  #             .groups = "drop") %>% 
  #   group_by(Responses) %>% 
  #   summarise(N = n(),
  #             trialid = paste(trialid, collapse = ", "), 
  #             .groups = "drop") %>% 
  #   DT::datatable()
```

